import swaggerAutogen from "swagger-autogen";

const outPutFile = "./src/swagger-autogen.json";

const endPointFile = ["./src/routes/router.ts"];


const doc = {
    info: {
      version: "1.0.0",
      title: "Team Manager API",
      description:
        "Documentation for a Team Manager automatically generated by the <b>swagger-autogen</b> module.",
    },
    host: "localhost:3001",
    basePath: "/",
    schemes: ["http"],
    consumes: ["application/json"],
    produces: ["application/json"],
    tags: [
      {
        name: ["Users", "Teams"],
        description: "Endpoints",
      },
    ],
    definitions: {
      User: {
        id: "3e5daa5e-ac58-4f19-a89f-017b6c313c4c",
        username: "alpha",
        email: "alpha@alpha.com",
        firstName: "Alpha",
        lastName: "Edtech",
        password: "12345",
        isAdmin: "false",
      },
      teams: {
        id: "c33a19a6-41cf-45af-9200-756d7371a",
        name: "Grupo Alpha",
        leader: "3e5daa5e-ac58-4f19-a89f-017b6c313c4c",
      },
    },
  };







swaggerAutogen(outPutFile, endPointFile, doc);





